namespace CodeMedic.Abstractions.Plugins;

/// <summary>
/// Interface for reporter plugins that format and output analysis results.
/// </summary>
public interface IReporterPlugin : IPlugin
{
    /// <summary>
    /// Gets the output format this reporter produces (e.g., "json", "markdown", "html").
    /// </summary>
    string OutputFormat { get; }

    /// <summary>
    /// Gets the file extension for reports generated by this reporter (e.g., ".json", ".md").
    /// </summary>
    string FileExtension { get; }

    /// <summary>
    /// Formats the analysis result and returns it as a string.
    /// </summary>
    /// <param name="analysisResult">The analysis result to format.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Formatted output as a string.</returns>
    Task<string> FormatAsync(object analysisResult, CancellationToken cancellationToken = default);

    /// <summary>
    /// Writes the formatted report to the specified output path.
    /// </summary>
    /// <param name="analysisResult">The analysis result to format and write.</param>
    /// <param name="outputPath">The file path to write the report to.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task WriteReportAsync(object analysisResult, string outputPath, CancellationToken cancellationToken = default);
}
